version: "3"
services:
  db:
    image: postgres:9.6
    restart: always
    environment:
      POSTGRES_PASSWORD: zedacarga
      POSTGRES_DB: zedacarga
    ports:
      - 5435:5432
    volumes:
      - ./postgres-data:/bitnami/postgresql/data 