spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/zedacarga"
    username: postgres
    password: zedacarga
    driver-class-name: org.postgresql.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: zedacargaltda@gmail.com
    password: xssp hsrz fcnd fxur
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8443
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: 122604Fqv@
    key-store-type: PKCS12
    key-alias: tomcat
    enabled: true
